/**
 * @module data.js
 */

/**
 * @typedef {Array} - data for table render
 */

export default [{
        "id": 0,
        "name": "WP Content Copy Protection & No Right Click",
        "link": "https://wordpress.org/plugins/wp-content-copy-protector/",
        "compatibility": "5.7.1",
        "screenshot": false,
        "mobile": true,
        "rightClick": true,
        "textSelection": true,
        "F12": false,
        "ctrlShiftI": true,
        "ctrlU": true,
        "ctrlACVX": true,
        "ctrlS": true,
        "ctrlP": true,
        "popularity": 100000,
        "note": "мешает работе js скриптов, сломал виртуальную клавиатуру",
    },

    {
        "id": 1,
        "name": "WP Content Copy Protection",
        "link": "https://wordpress.org/plugins/wp-content-copy-protection/",
        "compatibility": "5.7.1",
        "screenshot": false,
        "mobile": true,
        "rightClick": true,
        "textSelection": true,
        "F12": true,
        "ctrlShiftI": false,
        "ctrlU": true,
        "ctrlACVX": true,
        "ctrlS": false,
        "ctrlP": true,
        "popularity": 20000,
        "note": "иногда срабатывает печать, в Firefox работает Ctrl Shift S",
    },

    {
        "id": 2,
        "name": "WP Content Copy Protection with Color Design",
        "link": "https://wordpress.org/plugins/wp-copy-protect-with-color-design/",
        "compatibility": "5.7.1",
        "screenshot": false,
        "mobile": true,
        "rightClick": true,
        "textSelection": true,
        "F12": false,
        "ctrlShiftI": false,
        "ctrlU": false,
        "ctrlACVX": true,
        "ctrlS": false,
        "ctrlP": false,
        "popularity": 8000,
        "note": "F12 можно отключить в версии Pro",
    },

    {
        "id": 3,
        "name": "WP Protect Content",
        "link": "https://wordpress.org/plugins/wp-protect-content/",
        "compatibility": "5.7.1",
        "screenshot": false,
        "mobile": true,
        "rightClick": true,
        "textSelection": true,
        "F12": false,
        "ctrlShiftI": false,
        "ctrlU": false,
        "ctrlACVX": true,
        "ctrlS": false,
        "ctrlP": false,
        "popularity": 1000,
        "note": "F12 и Ctrl Shift I срабатывают через раз",
    },

    {
        "id": 4,
        "name": "Amazing Content Protector",
        "link": "",
        "compatibility": "5.6.3",
        "screenshot": false,
        "mobile": true,
        "rightClick": true,
        "textSelection": true,
        "F12": true,
        "ctrlShiftI": false,
        "ctrlU": true,
        "ctrlACVX": true,
        "ctrlS": true,
        "ctrlP": true,
        "popularity": 100,
        "note": "в Firefox работает Ctrl Shift S",
    },

    {
        "id": 5,
        "name": "WP-Copyright-Protection",
        "link": "https://wordpress.org/plugins/wp-copyright-protection/",
        "compatibility": "5.3.7",
        "screenshot": false,
        "mobile": true,
        "rightClick": true,
        "textSelection": true,
        "F12": false,
        "ctrlShiftI": false,
        "ctrlU": false,
        "ctrlACVX": true,
        "ctrlS": false,
        "ctrlP": false,
        "popularity": 10000,
        "note": "",
    },

    {
        "id": 6,
        "name": "Secure Copy Content Protection and Content Locking",
        "link": "https://wordpress.org/plugins/secure-copy-content-protection/",
        "compatibility": "5.7.1",
        "screenshot": false,
        "mobile": true,
        "rightClick": true,
        "textSelection": true,
        "F12": true,
        "ctrlShiftI": true,
        "ctrlU": true,
        "ctrlACVX": true,
        "ctrlS": true,
        "ctrlP": false,
        "popularity": 10000,
        "note": "",
    },

    {
        "id": 7,
        "name": "WP Copy Content Protection",
        "link": "https://wordpress.org/plugins/wp-copy-content-protection/",
        "compatibility": "5.6.3",
        "screenshot": false,
        "mobile": true,
        "rightClick": true,
        "textSelection": true,
        "F12": false,
        "ctrlShiftI": true,
        "ctrlU": true,
        "ctrlACVX": true,
        "ctrlS": true,
        "ctrlP": true,
        "popularity": 800,
        "note": "",
    },

    {
        "id": 8,
        "name": "CopySafe Web Protection",
        "link": "",
        "compatibility": "5.6.3",
        "screenshot": undefined,
        "mobile": undefined,
        "rightClick": undefined,
        "textSelection": undefined,
        "F12": undefined,
        "ctrlShiftI": undefined,
        "ctrlU": undefined,
        "ctrlACVX": undefined,
        "ctrlS": undefined,
        "ctrlP": undefined,
        "popularity": 900,
        "note": "требует установки своего софта (браузера)",
    },

    {
        "id": 9,
        "name": "All In One WP Security & Firewall",
        "link": "https://ru.wordpress.org/plugins/all-in-one-wp-security-and-firewall/",
        "compatibility": "5.7.1",
        "screenshot": false,
        "mobile": true,
        "rightClick": undefined,
        "textSelection": true,
        "F12": false,
        "ctrlShiftI": false,
        "ctrlU": false,
        "ctrlACVX": undefined,
        "ctrlS": undefined,
        "ctrlP": true,
        "popularity": 900000,
        "note": "многофункциональный плагин, нет смысла ставить только ради контента, работает нестабильно, не поддерживает Chromium, есть ошибки в Chrome, ошибки с правым кликом, Ctrl S, Ctrl Shift P",
    },


    {
        "id": 10,
        "name": "Disable Right Click For WP",
        "link": "https://wordpress.org/plugins/disable-right-click-for-wp/",
        "compatibility": "5.7.1",
        "screenshot": false,
        "mobile": true,
        "rightClick": true,
        "textSelection": true,
        "F12": true,
        "ctrlShiftI": true,
        "ctrlU": true,
        "ctrlACVX": true,
        "ctrlS": false,
        "ctrlP": false,
        "popularity": 20000,
        "note": "",
    },

    {
        "id": 11,
        "name": "Copyright Proof",
        "link": "https://wordpress.org/plugins/digiproveblog/",
        "compatibility": "5.6.3",
        "screenshot": false,
        "mobile": true,
        "rightClick": true,
        "textSelection": true,
        "F12": false,
        "ctrlShiftI": false,
        "ctrlU": true,
        "ctrlACVX": true,
        "ctrlS": false,
        "ctrlP": false,
        "popularity": 3000,
        "note": "бесплатная версия ограничена сроком 1 месяц",
    },

    {
        "id": 12,
        "name": "Disable Right Click and Content Copy Protection",
        "link": "https://wordpress.org/plugins/disable-right-click-and-content-copy-protection/",
        "compatibility": "5.7.1",
        "screenshot": false,
        "mobile": false,
        "rightClick": true,
        "textSelection": true,
        "F12": false,
        "ctrlShiftI": true,
        "ctrlU": true,
        "ctrlACVX": true,
        "ctrlS": true,
        "ctrlP": false,
        "popularity": 900,
        "note": "блокирует работу js, мешал виртуальной клавиатуре в Chrome",
    },

    {
        "id": 13,
        "name": "Mechanic No Right Click",
        "link": "https://wordpress.org/plugins/bmt-no-right-click/",
        "compatibility": "5.5.4",
        "screenshot": false,
        "mobile": false,
        "rightClick": true,
        "textSelection": true,
        "F12": true,
        "ctrlShiftI": false,
        "ctrlU": true,
        "ctrlACVX": true,
        "ctrlS": false,
        "ctrlP": true,
        "popularity": 400,
        "note": "текст визуально выделяет, но копирования не происходит",
    },

]